# mysql

services:
   mysql:
      image: mysql:latest
      environment:
         MYSQL_ROOT_PASSWORD: docker
         MYSQL_DATABASE: docker
      ports:
         - '3306:3306'
      volumes:
         - mysql:/var/lib/mysql

volumes:
   mysql:
      driver: local
